services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
#  reverse-proxy:
#    build:
#      context: Frontend/Web
#      dockerfile: Development.Dockerfile
#    ports:
#      - "8080:8080"
#      - "8443:8443"
#    environment:
#      - HTTP_PORT=8080
#      - HTTPS_PORT=8443
volumes:
  pgdata: