services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  fashionpicker.api:
    container_name: api
    build:
      context: .
      dockerfile: FashionPicker.Api/Dockerfile
    env_file:
      - ./secrets/fashion-picker.env

  fashionpicker.filerepository:
    container_name: file-repository
    build:
      context: .
      dockerfile: FashionPicker.FileRepository/Dockerfile
    env_file:
      - ./secrets/file-repository.env

    volumes:
      - type: bind
        source: "${STATIC_HOST_PATH}"
        target: /var/lib/filerepository

  fashionpicker.reverseproxy:
    container_name: reverse-proxy
    build:
      context: .
      dockerfile: Fashionpicker.ReverseProxy/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - "${REVERSE_PROXY_ENV}"

volumes:
  pgdata: