services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  fashionpicker.api:
    build:
      context: .
      dockerfile: FashionPicker.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - ./secrets/fashion-picker.env

  fashionpicker.filerepository:
    build:
      context: .
      dockerfile: FashionPicker.FileRepository/Dockerfile
    ports:
      - "8090:8080"
      - "8091:8081"
    env_file:
      - ./secrets/file-repository.env
    volumes:
      - frdata:/var/lib/filerepository

volumes:
  pgdata:
  frdata: