// <auto-generated />
using System;
using FashionPicker.Infra.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FashionPicker.Infra.Migrations
{
    [DbContext(typeof(OutfitDbContext))]
    partial class OutfitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FashionPicker.Infra.Models.Outfit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OutfitCreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutfitDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutfitImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutfitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutfitSeason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("FashionPicker.Infra.Models.OutfitTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OutfitId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OutfitId");

                    b.ToTable("OutfitTags");
                });

            modelBuilder.Entity("FashionPicker.Infra.Models.OutfitTag", b =>
                {
                    b.HasOne("FashionPicker.Infra.Models.Outfit", null)
                        .WithMany("OutfitTags")
                        .HasForeignKey("OutfitId");
                });

            modelBuilder.Entity("FashionPicker.Infra.Models.Outfit", b =>
                {
                    b.Navigation("OutfitTags");
                });
#pragma warning restore 612, 618
        }
    }
}
