// <auto-generated />
using System;
using FashionPicker.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FashionPicker.Infrastructure.Migrations
{
    [DbContext(typeof(OutfitDbContext))]
    partial class OutfitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FashionPicker.Core.Objects.Clothing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clothing");
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.ClothingImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClothingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClothingId");

                    b.ToTable("ClothingImage");
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.Outfit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Mood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Sport")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Outfits");
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.OutfitColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutfitColor");
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.OutfitImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OutfitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OutfitId");

                    b.ToTable("OutfitImage");
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.OutfitTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("OutfitTags");
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("OutfitOutfitColor", b =>
                {
                    b.Property<Guid>("ColorsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OutfitsId")
                        .HasColumnType("uuid");

                    b.HasKey("ColorsId", "OutfitsId");

                    b.HasIndex("OutfitsId");

                    b.ToTable("OutfitOutfitColor");
                });

            modelBuilder.Entity("OutfitOutfitTag", b =>
                {
                    b.Property<Guid>("OutfitsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("OutfitsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("OutfitOutfitTag");
                });

            modelBuilder.Entity("OutfitSeason", b =>
                {
                    b.Property<Guid>("OutfitsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonsId")
                        .HasColumnType("uuid");

                    b.HasKey("OutfitsId", "SeasonsId");

                    b.HasIndex("SeasonsId");

                    b.ToTable("OutfitSeason");
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.ClothingImage", b =>
                {
                    b.HasOne("FashionPicker.Core.Objects.Clothing", "Clothing")
                        .WithMany("Images")
                        .HasForeignKey("ClothingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clothing");
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.OutfitImage", b =>
                {
                    b.HasOne("FashionPicker.Core.Objects.Outfit", "Outfit")
                        .WithMany("Images")
                        .HasForeignKey("OutfitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outfit");
                });

            modelBuilder.Entity("OutfitOutfitColor", b =>
                {
                    b.HasOne("FashionPicker.Core.Objects.OutfitColor", null)
                        .WithMany()
                        .HasForeignKey("ColorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionPicker.Core.Objects.Outfit", null)
                        .WithMany()
                        .HasForeignKey("OutfitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OutfitOutfitTag", b =>
                {
                    b.HasOne("FashionPicker.Core.Objects.Outfit", null)
                        .WithMany()
                        .HasForeignKey("OutfitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionPicker.Core.Objects.OutfitTag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OutfitSeason", b =>
                {
                    b.HasOne("FashionPicker.Core.Objects.Outfit", null)
                        .WithMany()
                        .HasForeignKey("OutfitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FashionPicker.Core.Objects.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.Clothing", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("FashionPicker.Core.Objects.Outfit", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
